Motd: '&aNinho&eBACK &aServidores de PvP'
StatusMotd: '&b&l&k!!!&aESTAMOS DE, VOLTA!&b&l&k!!!'
NomeServer: '&aNinho&eBACK'
MensagemAutomatica1: 'Em DESEMVOLVIMENTO!'
MensagemAutomatica2: 'Em DESEMVOLVIMENTO!'
MensagemAutomatica3: 'Em DESEMVOLVIMENTO!'
MensagemAutomatica4: 'Em DESEMVOLVIMENTO!'
MensagemAutomatica5: 'Em DESEMVOLVIMENTO!'
MensagemAplicar1: '&bAplique-se no link: sem formulario por enquanto'
MensagemYoutuber1: '&bPara se tornar YT No Servidor Necessita-se de 250 Subs + Video No Servidor'
MensagemYoutuber2: '&cEssa TAG Não é Liberada'
MensagemYoutuber3: '&cEssa TAG Não é Liberada'
